/*
 * Copyright 2021 Matt Jamesson <scifidryer@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package protocolwhisperer.drivers;

/**
 *
 * @author Matt Jamesson <scifidryer@gmail.com>
 */
public class CIPConfigFrame extends javax.swing.JFrame {

    /**
     * Creates new form CIPConfigFrame
     */
    CIPProtocolRecord currentRecord = null;
    public CIPConfigFrame(CIPProtocolRecord aCurrentRecord) {
        initComponents();
        currentRecord = aCurrentRecord;
        if (currentRecord.configured)
        {
            cipHostField.setText(currentRecord.host);
            cipSlotField.setText(currentRecord.slot + "");
            cipTagField.setText(currentRecord.cipTag);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cipHostField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cipSlotField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cipTagField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("CIP Host:");
        jPanel1.add(jLabel1);

        cipHostField.setColumns(10);
        jPanel1.add(cipHostField);

        jLabel3.setText("Slot:");
        jPanel1.add(jLabel3);

        cipSlotField.setColumns(2);
        cipSlotField.setText("0");
        cipSlotField.setToolTipText("");
        jPanel1.add(cipSlotField);

        getContentPane().add(jPanel1);

        jLabel2.setText("CIP Tag:");
        jPanel3.add(jLabel2);

        cipTagField.setColumns(20);
        jPanel3.add(cipTagField);

        getContentPane().add(jPanel3);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel2.add(okButton);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        currentRecord.host = cipHostField.getText();
        currentRecord.cipTag = cipTagField.getText();
        currentRecord.slot = Integer.parseInt(cipSlotField.getText());
        currentRecord.configured = true;
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cipHostField;
    private javax.swing.JTextField cipSlotField;
    private javax.swing.JTextField cipTagField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
